Updated provider apply

diff --git a/.github/workflows/crossplane-install.yml b/.github/workflows/crossplane-install.yml
--- a/.github/workflows/crossplane-install.yml
+++ b/.github/workflows/crossplane-install.yml
@@ -29,14 +29,14 @@ jobs:
           kubectl create namespace crossplane-system --dry-run=client -o yaml | kubectl apply -f -
           if kubectl get deployment crossplane -n crossplane-system >/dev/null 2>&1 && \
             kubectl wait --for=condition=available deployment/crossplane -n crossplane-system >/dev/null --timeout 5m 2>&1; then
-            echo "Crossplane is already installed and healthy, skipping installation."
+            echo "Crossplane is already installed and healthy, skipping installation"
           else
             echo "Crossplane not found or not healthy, installing..."
             helm repo add crossplane-stable https://charts.crossplane.io/stable
             helm repo update
             if helm list -n crossplane-system | grep -q "crossplane"; then
               echo "Removing existing Helm release 'crossplane'..."
-              helm uninstall crossplane -n crossplane-system --wait || echo "Uninstall failed, proceeding with install"
+              helm uninstall crossplane -n crossplane-system --wait || echo "Uninstall failed, proceeding with installation"
             fi
             helm install crossplane --namespace crossplane-system crossplane-stable/crossplane --version 1.14.0
           fi
diff --git a/.github/workflows/kyverno-install.yml b/.github/workflows/kyverno-install.yml
--- a/.github/workflows/kyverno-install.yml
+++ b/.github/workflows/kyverno-install.yml
@@ -29,14 +29,14 @@ jobs:
           kubectl create namespace kyverno --dry-run=client -o yaml | kubectl apply -f -
           if kubectl get deployment kyverno -n kyverno >/dev/null 2>&1 && \
             kubectl wait --for=condition=available deployment/kyverno -n kyverno >/dev/null --timeout 5m 2>&1; then
-            echo "Kyverno is already installed and healthy, skipping installation."
+            echo "Kyverno is already installed and healthy, skipping installation"
           else
             echo "Kyverno not found or not healthy, installing..."
             helm repo add kyverno https://kyverno.github.io/kyverno/
             helm repo update
             if helm list -n kyverno | grep -q "kyverno"; then
               echo "Removing existing Helm release 'kyverno'..."
-              helm uninstall kyverno -n kyverno --wait || echo "Uninstall failed, proceeding with install"
+              helm uninstall kyverno -n kyverno --wait || echo "Uninstall failed, proceeding with installation"
             fi
             helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace
           fi
